version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    environment:
      - MONGO_URI=mongodb://ReaTiMo:hoangtien123@54.221.183.93:27017/todo?authSource=admin
      - JWT_SECRET=BI_MAT
      - PORT=8000
    # THÊM PHẦN NÀY VÀO:
    volumes:
      - ./backend:/app
      - /app/node_modules # Giữ node_modules của Linux, không cho Windows đè vào
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    # THÊM PHẦN NÀY VÀO:
    volumes:
      - ./frontend:/app
      - /app/node_modules # Giữ node_modules của Linux
    depends_on:
      - backend